In [ ]:
import torch
x = torch.arange(10)
x, id(x), type(x)


(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 4957657904, torch.Tensor)

In [6]:
import torch 
x = torch.tensor(10)
print(id(x))
x = x + 1
id(x)

5772541488


5772535568

In [10]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x,y), x*y, torch.sum(x*y)

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor(6.),
 tensor([0., 1., 2., 3.]),
 tensor(6.))

In [ ]:
import torch
A = torch.arange(10, dtype=torch.float64).reshape(2,5)
x = torch.arange(5, dtype=torch.float64)
A.shape, x.shape, torch.mv(A,x)

In [12]:
import torch
A = torch.arange(10, dtype=torch.float64).reshape(2,5)
B = torch.arange(10, dtype=torch.float64).reshape(5, 2)
torch.mm(A, B), torch.mm(A, B).shape

(tensor([[ 60.,  70.],
         [160., 195.]], dtype=torch.float64),
 torch.Size([2, 2]))

In [14]:
import torch
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()

(tensor(5.), tensor(7.))

In [16]:
import torch
torch.norm(torch.ones((5,4)))

tensor(4.4721)

In [17]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [27]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True)
x.grad, x.requires_grad

(None, True)

In [28]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [29]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [30]:
x.grad == 4*x

tensor([True, True, True, True])

In [31]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [ ]:
y = x.sum()
y.backward()
x.grad # Cumulative Gradient

tensor([3., 3., 3., 3.])

In [35]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()
y = x * x
u = y.detach()
v = y.detach_() # separation calculation
z = u*x
z.sum().backward()
x, u, v, u==v, x.grad == u

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.]),
 tensor([0., 1., 4., 9.]),
 tensor([True, True, True, True]),
 tensor([True, True, True, True]))

In [46]:
# Gradient calculation under control flow
import torch
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(1, requires_grad=True)
d = f(a)
print(d)
d.backward()
a.grad, a.grad == d/a

tensor([1374.7246], grad_fn=<MulBackward0>)


(tensor([1024.]), tensor([True]))

In [52]:
import torch
fair_probs = torch.ones(6)/6
fair_probs, torch.distributions.multinomial.Multinomial(1, fair_probs).sample()

(tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]),
 tensor([0., 1., 0., 0., 0., 0.]))

In [53]:
torch.distributions.multinomial.Multinomial(10, fair_probs).sample()

tensor([1., 2., 1., 2., 2., 2.])

In [54]:
torch.distributions.multinomial.Multinomial(1000, fair_probs).sample()/1000

tensor([0.1950, 0.1400, 0.1740, 0.1470, 0.1710, 0.1730])

In [55]:
torch.distributions.multinomial.Multinomial(10000, fair_probs).sample()/10000

tensor([0.1612, 0.1673, 0.1629, 0.1693, 0.1678, 0.1715])

In [61]:
torch.distributions.multinomial.Multinomial(10000, fair_probs).sample()/10000

tensor([0.1618, 0.1634, 0.1670, 0.1660, 0.1751, 0.1667])

In [72]:
counts = torch.distributions.multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
cum_counts, cum_counts/cum_counts.sum(dim=1,keepdim=True)

(tensor([[  2.,   3.,   1.,   2.,   0.,   2.],
         [  4.,   5.,   2.,   3.,   1.,   5.],
         [  4.,   8.,   6.,   3.,   3.,   6.],
         ...,
         [863., 833., 806., 826., 869., 783.],
         [864., 834., 807., 830., 870., 785.],
         [864., 837., 807., 833., 871., 788.]]),
 tensor([[0.2000, 0.3000, 0.1000, 0.2000, 0.0000, 0.2000],
         [0.2000, 0.2500, 0.1000, 0.1500, 0.0500, 0.2500],
         [0.1333, 0.2667, 0.2000, 0.1000, 0.1000, 0.2000],
         ...,
         [0.1733, 0.1673, 0.1618, 0.1659, 0.1745, 0.1572],
         [0.1731, 0.1671, 0.1617, 0.1663, 0.1743, 0.1573],
         [0.1728, 0.1674, 0.1614, 0.1666, 0.1742, 0.1576]]))

In [74]:
dir(torch.distributions)

['AbsTransform',
 'AffineTransform',
 'Bernoulli',
 'Beta',
 'Binomial',
 'CatTransform',
 'Categorical',
 'Cauchy',
 'Chi2',
 'ComposeTransform',
 'ContinuousBernoulli',
 'CorrCholeskyTransform',
 'CumulativeDistributionTransform',
 'Dirichlet',
 'Distribution',
 'ExpTransform',
 'Exponential',
 'ExponentialFamily',
 'FisherSnedecor',
 'Gamma',
 'Geometric',
 'Gumbel',
 'HalfCauchy',
 'HalfNormal',
 'Independent',
 'IndependentTransform',
 'InverseGamma',
 'Kumaraswamy',
 'LKJCholesky',
 'Laplace',
 'LogNormal',
 'LogisticNormal',
 'LowRankMultivariateNormal',
 'LowerCholeskyTransform',
 'MixtureSameFamily',
 'Multinomial',
 'MultivariateNormal',
 'NegativeBinomial',
 'Normal',
 'OneHotCategorical',
 'OneHotCategoricalStraightThrough',
 'Pareto',
 'Poisson',
 'PositiveDefiniteTransform',
 'PowerTransform',
 'RelaxedBernoulli',
 'RelaxedOneHotCategorical',
 'ReshapeTransform',
 'SigmoidTransform',
 'SoftmaxTransform',
 'SoftplusTransform',
 'StackTransform',
 'StickBreakingTransform',


In [77]:
help(torch.ones)

Help on built-in function ones in module torch:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the curre

In [81]:
a = torch.rand((4,5))
b = torch.rand((5,4))
torch.mm(a,b), torch.matmul(a,b), torch.mm(a,b)==torch.matmul(a,b)

(tensor([[1.4210, 1.4360, 1.0978, 1.2428],
         [0.7827, 1.1547, 0.5474, 0.9985],
         [1.4665, 1.4864, 1.2686, 1.2392],
         [1.2465, 1.1345, 1.0983, 0.9681]]),
 tensor([[1.4210, 1.4360, 1.0978, 1.2428],
         [0.7827, 1.1547, 0.5474, 0.9985],
         [1.4665, 1.4864, 1.2686, 1.2392],
         [1.2465, 1.1345, 1.0983, 0.9681]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
a = torch.rand((2,2,3))
b = torch.rand((2,3,1)) # 支持batch维度
torch.matmul(a,b), a@b, a@b == torch.matmul(a,b)

(tensor([[[1.2874],
          [0.4446]],
 
         [[0.6243],
          [0.6451]]]),
 tensor([[[1.2874],
          [0.4446]],
 
         [[0.6243],
          [0.6451]]]),
 tensor([[[True],
          [True]],
 
         [[True],
          [True]]]))

In [94]:
a = torch.rand((2,2,3))
b = torch.rand((3,1)) # 支持broadcast
torch.matmul(a,b), a@b, a@b == torch.matmul(a,b)

(tensor([[[0.7708],
          [1.5376]],
 
         [[1.4445],
          [0.6799]]]),
 tensor([[[0.7708],
          [1.5376]],
 
         [[1.4445],
          [0.6799]]]),
 tensor([[[True],
          [True]],
 
         [[True],
          [True]]]))

In [101]:
a = torch.rand(4)
b = torch.rand(4)
a*b,a@b,torch.dot(a,b), torch.matmul(a,b)# 支持n维度，这里就是1D计算，这里也等价于点积

(tensor([0.0032, 0.0545, 0.0713, 0.1690]),
 tensor(0.2980),
 tensor(0.2980),
 tensor(0.2980))

In [106]:
print("transforms" in dir(torch.utils))

False


In [112]:
import torch
from torch import nn
import torchvision
from torch.utils import data
from torchvision import transforms
trans = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(
root="data", train=True, transform=trans, download=True)
# transforms.Compose
# nn.Flatten() 默认第一维不动，剩下的展平
net = nn.Linear(10, 1)
net.parameters()# 生成器

<generator object Module.parameters at 0x17fdeace0>

In [122]:
n1 = nn.Linear(10,1)
nn.init.normal_(n1.weight, std=1)
net = nn.Sequential(nn.Flatten(),
                    nn.Linear(784, 256),
                    nn.ReLU(),
                    nn.Linear(256, 10))
def init_weights(m):
    print(type(m))
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, std=0.01)
net.apply(init_weights)

<class 'torch.nn.modules.flatten.Flatten'>
<class 'torch.nn.modules.linear.Linear'>
<class 'torch.nn.modules.activation.ReLU'>
<class 'torch.nn.modules.linear.Linear'>
<class 'torch.nn.modules.container.Sequential'>


Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=256, bias=True)
  (2): ReLU()
  (3): Linear(in_features=256, out_features=10, bias=True)
)

In [125]:
torch.rand((10, 2)).uniform_(0,1)
# 函数以dropout的概率丢弃张量输入X中的元素，如 上所述重新缩放剩余部分:将剩余部分除以1.0-dropout
# 先激活-再丢弃

tensor([[0.6874, 0.3600],
        [0.9643, 0.6105],
        [0.8612, 0.4402],
        [0.4808, 0.2397],
        [0.0232, 0.4268],
        [0.4110, 0.3270],
        [0.4997, 0.0017],
        [0.0882, 0.2303],
        [0.5483, 0.4442],
        [0.5333, 0.0370]])

In [ ]:
x = torch.arange(-8.0, 8.0, 0.1, requires_grad=True) 
y = torch.sigmoid(x)
y.backward(torch.ones_like(x)) # 这里等价于y.sum().backward()
x.grad

tensor([0.0003, 0.0004, 0.0004, 0.0005, 0.0005, 0.0006, 0.0006, 0.0007, 0.0007,
        0.0008, 0.0009, 0.0010, 0.0011, 0.0012, 0.0014, 0.0015, 0.0017, 0.0018,
        0.0020, 0.0022, 0.0025, 0.0027, 0.0030, 0.0033, 0.0037, 0.0041, 0.0045,
        0.0049, 0.0055, 0.0060, 0.0066, 0.0073, 0.0081, 0.0089, 0.0099, 0.0109,
        0.0120, 0.0132, 0.0146, 0.0160, 0.0177, 0.0194, 0.0214, 0.0235, 0.0259,
        0.0285, 0.0313, 0.0343, 0.0376, 0.0412, 0.0452, 0.0494, 0.0540, 0.0590,
        0.0644, 0.0701, 0.0763, 0.0828, 0.0898, 0.0972, 0.1050, 0.1132, 0.1217,
        0.1306, 0.1398, 0.1491, 0.1587, 0.1683, 0.1779, 0.1874, 0.1966, 0.2055,
        0.2139, 0.2217, 0.2288, 0.2350, 0.2403, 0.2445, 0.2475, 0.2494, 0.2500,
        0.2494, 0.2475, 0.2445, 0.2403, 0.2350, 0.2288, 0.2217, 0.2139, 0.2055,
        0.1966, 0.1874, 0.1779, 0.1683, 0.1587, 0.1491, 0.1398, 0.1306, 0.1217,
        0.1132, 0.1050, 0.0972, 0.0898, 0.0828, 0.0763, 0.0701, 0.0644, 0.0590,
        0.0540, 0.0494, 0.0452, 0.0412, 

In [ ]:
import requests
# requests.get(url,)

Help on function get in module requests.api:

get(url, params=None, **kwargs)
    Sends a GET request.

    :param url: URL for the new :class:`Request` object.
    :param params: (optional) Dictionary, list of tuples or bytes to send
        in the query string for the :class:`Request`.
    :param \*\*kwargs: Optional arguments that ``request`` takes.
    :return: :class:`Response <Response>` object
    :rtype: requests.Response



(None,
 ['__annotations__',
  '__builtins__',
  '__call__',
  '__class__',
  '__closure__',
  '__code__',
  '__defaults__',
  '__delattr__',
  '__dict__',
  '__dir__',
  '__doc__',
  '__eq__',
  '__format__',
  '__ge__',
  '__get__',
  '__getattribute__',
  '__getstate__',
  '__globals__',
  '__gt__',
  '__hash__',
  '__init__',
  '__init_subclass__',
  '__kwdefaults__',
  '__le__',
  '__lt__',
  '__module__',
  '__name__',
  '__ne__',
  '__new__',
  '__qualname__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__setattr__',
  '__sizeof__',
  '__str__',
  '__subclasshook__',
  '__type_params__'])

In [ ]:
import torch
# x = torch.randn((2), requires_grad=True)
x = torch.arange(4.0, requires_grad=True)
y = torch.dot(x, x)
y.sum()
y.backward()
x.grad, type(x.grad)

(tensor([0., 2., 4., 6.]), torch.Tensor)

In [164]:
import torch
x = torch.tensor(3)
x.detach(), x.item()
torch.utils.data.BatchSampler
torch.argmax

<function torch._VariableFunctionsClass.argmax>

In [168]:
a = torch.randn(4, 4)
a, a[0,1], torch.argmax(a, dim=1)

(tensor([[ 0.2328, -0.5857, -0.0426, -0.7167],
         [ 0.4493,  1.7353, -0.4943, -0.5761],
         [-1.9561,  0.2181, -0.9514, -1.3242],
         [-0.8983,  0.8185, -1.0535, -0.4874]]),
 tensor(-0.5857),
 tensor([0, 1, 1, 1]))

In [173]:
from soft_max.manual_implementation.model import LinRegSm
net = LinRegSm(10, 1)
ps = net.parameters()
net2 = torch.nn.Linear(10,1)
ps2 = net2.parameters()
[p for p in ps], [p for p in ps2]


([],
 [Parameter containing:
  tensor([[ 0.1845, -0.1414, -0.0279,  0.2866,  0.1852,  0.2434, -0.1465,  0.1503,
            0.2116, -0.2075]], requires_grad=True),
  Parameter containing:
  tensor([-0.0099], requires_grad=True)])

In [179]:
from collections import defaultdict
a = defaultdict()
a["sd"].update(10)

KeyError: 'sd'

In [182]:
a={"sd":1}
a["sd"].update(10)

AttributeError: 'int' object has no attribute 'update'

In [184]:
from util.misc import SmoothedValue
from collections import defaultdict
a = defaultdict(SmoothedValue)
a["k"].update(10), a

(None,
 defaultdict(util.misc.SmoothedValue,
             {'k': <util.misc.SmoothedValue at 0x16010a180>}))

In [192]:
from util.misc import MetricLogger
m = MetricLogger()
m.__dict__, type(m).__name__, m.__class__.__name__

({'meters': defaultdict(util.misc.SmoothedValue, {}), 'delimiter': '\t'},
 'MetricLogger',
 'MetricLogger')

In [198]:
import datetime
eta_seconds = 100
t = datetime.timedelta(seconds=int(eta_seconds))
t.__str__()

'0:01:40'

In [201]:
from soft_max.manual_implementation.model import LinRegSm
model = LinRegSm(10,2)
k="ds"
"_".join([model.__class__.__name__, k])

'LinRegSm_ds'

In [ ]:
fmt="{median:.4f}"
fmt.format(median=8.234)

'8.2340'